#!/bin/bash

#####
#
# This wrapper script can be cusotmized for your solution, however, we expect
# that it will work out of the box for you.
#
# To use, simply:
#
#   1. modify count_404s.cpp
#   2. run ./count_404s
#
#####

DIRNAME="$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")"
[[ -z "$NOREMAKE" && -e "$DIRNAME/Makefile" ]] && (cd "$DIRNAME" && make count_404s.o)
exec "$DIRNAME/count_404s.o" "$@"
