#!/bin/bash

#####
#
# This wrapper script can be cusotmized for your solution, however, we expect
# that it will work out of the box for you.
#
# To use, simply:
#
#   1. modify histogram.cpp
#   2. run ./histogram
#
#####

DIRNAME="$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")"
[[ -z "$NOREMAKE" && -e "$DIRNAME/Makefile" ]] && (cd "$DIRNAME" && make histogram.o)
exec "$DIRNAME/histogram.o" "$@"
